### ISSUE TITLE
When will the trained weights be released

### ISSUE THREAD

**Issue by hahans** [ZCMax/LLaVA-3D#1]
I wish I could use this masterpiece sooner

**Comment by ZCMax** [comment]
Hello Thanks for your attention, we will release the detailed demo script and tutorial and the checkpoints on hugging face in the next week, stay tuned~

**Comment by ZCMax** [comment]
We've released our checkpoint on huggingface and the demo script, feel free to try it! And we'll continue to update the evaluation script on various benchmarks in the next week~
