### ISSUE TITLE
The details aboud training data in the stage1 alignment 

### ISSUE THREAD

**Issue by SiyuanWei** [ZCMax/LLaVA-3D#10]
Hi, could you please give some details aboud the training data in the stage1? Does the caption data come from all the 3d-to-txt style dataset in the LLaVA-3D-Instruct-1M ?
![image](https://github.com/user-attachments/assets/152283b7-9f84-420d-b7e0-70d0bfd66410)
![image](https://github.com/user-attachments/assets/ca124ad2-0a62-4453-9646-989b1f79328b)

**Comment by ZCMax** [comment]
I don't quite understand the meaning of `come from all the 3d-to-txt style dataset in the LLaVA-3D-Instruct-1M`. The region-level and scene-level caption data are not included in the LLaVA-3D-Instruct-1M dataset.  For scene-level caption, we use the scene caption dataset from SceneVerse, and for the region-caption data, we use the data region-level caption from MMScan.

**Comment by SiyuanWei** [comment]
Sorry， I was trying to say "whether the stage1 training data is included in the LLAVA-3D-Instruct-1M". Thanks for you reply !
