### ISSUE TITLE
About Inference Time

### ISSUE THREAD

**Issue by KaKa-101** [ZCMax/LLaVA-3D#14]
Thanks for your great work. I see that LLaVA-3D achieves faster training and inference time. But I have a question about the definition of inference time: How do you define the inference time? the model forward time for one batch?
Could you give me a clear definition of the inference time? 
Looking forward to your reply.

**Comment by ZCMax** [comment]
Thanks for your question, the inference time denotes the average 3D scene feature extraction time for each scene, not including the LLM inference time~
