### ISSUE TITLE
About Training Data

### ISSUE THREAD

**Issue by LightManxx** [ZCMax/LLaVA-3D#15]
Hello, I am trying to make the dataset in the paper by myself. I found that the data in SceneVerse are all in point cloud format, without image, depth, etc. Does the original dataset contain these data or have you done other processing?

**Comment by ZCMax** [comment]
Thanks for your question~ We only use the language annotation from the SceneVerse dataset, which only provides the point cloud data,  you can find the image, depth, etc in [EmbodiedScan](https://github.com/OpenRobotLab/EmbodiedScan).
