### ISSUE TITLE
Stage1 trainining script

### ISSUE THREAD

**Issue by SiyuanWei** [ZCMax/LLaVA-3D#18]
Hi, thanks for releasing your training bash ! We've met some problems and it'll be nice to get your help. 
In the stage1 script (./scripts/train/pretrain.sh), we noticed that the "tune_video_tower" option is not enabled, which will freeze video_tower containing the weights from 3d patch pos embedding and 3d coordinate prompt encoder, but it says "We freeze the vision encoder and LLM parameters, and only train the projection layer and 3D position embedding layer, encouraging efficient alignment between 3D patch features and text space" in the paper. 
We're wondering if the script for stage1 is correct ( we think it might be proper to finetune both the mlp part and video_tower part in the first stage .)

![image](https://github.com/user-attachments/assets/260153da-2a8a-4ea2-9ec0-1b7380fceabc)

**Comment by ZCMax** [comment]
Yes you are definitely right, please refer to the https://github.com/ZCMax/LLaVA-3D/issues/16
