### ISSUE TITLE
Invalid Depth Issue

### ISSUE THREAD

**Issue by SiyuanWei** [ZCMax/LLaVA-3D#19]
Hi,  I've noticed that there is no code related to filter invalid depth values (including 0 / nan depth values). Do I miss any relevant codes or  the processing of model and video_processor does not contain this indeed?

**Comment by ZCMax** [comment]
Yes, currently there is no code for filtering invalid depth values, you need to inpaint the depth before sending it into model, such as [ODIN](https://github.com/ayushjain1144/odin/blob/af8995f45b1bce399d217ab66b46070caaa6fcbd/odin/utils/inpaint_depth.py#L15).

**Comment by SiyuanWei** [comment]
> Yes, currently there is no code for filtering invalid depth values, you need to inpaint the depth before sending it into model, such as [ODIN](https://github.com/ayushjain1144/odin/blob/af8995f45b1bce399d217ab66b46070caaa6fcbd/odin/utils/inpaint_depth.py#L15).

Thanks !
