### ISSUE TITLE
Axis alignment matrix

### ISSUE THREAD

**Issue by Yebulabula** [ZCMax/LLaVA-3D#22]
Dear author,

Thanks for your amazing work in 3D VLM field!

I have a question about the camera parameters you provided. May I ask how's the axis alignment matrix for a specific 3D scene calculated?

Best,
Ye

**Comment by ZCMax** [comment]
The meaning of axis-aligned is that the horizontal axes are typically aligned with the walls, and the vertical axis is aligned with the direction of gravity. The origin is typically set on/near the center of the floor. However, I don't calculate the matrix by myself, which has been provided in the original datasets. but maybe I could provide the code snippet for your reference.

```
import numpy as np

def compute_axis_aligned_matrix(points):
    mean = np.mean(points, axis=0)
    centered_points = points - mean
    cov_matrix = np.cov(centered_points.T)
    
    eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)
    
    R = eigenvectors.T
    
    if np.linalg.det(R) < 0:
        R[2] *= -1
    
    transform = np.eye(4)
    transform[:3, :3] = R
    transform[:3, 3] = -R @ mean
    
    return transform
```
Previous works for 3D detection typically convert the input point clouds to the axis-aligned coordinate system for easier 3D bounding box extraction.
