### ISSUE TITLE
在运行pip install -e ".[train]"时出错

### ISSUE THREAD

**Issue by WangXiuhao** [ZCMax/LLaVA-3D#4]
![image](https://github.com/user-attachments/assets/62325d41-686c-4628-b580-8c41bbac3c9c)
请问我应该怎么做呀，感谢！

**Comment by ZCMax** [comment]
请问你的环境是什么？是在 Windows 上安装吗

**Comment by WangXiuhao** [comment]
> 请问你的环境是什么？是在 Windows 上安装吗

感谢回复。我刚刚检查了一下，环境是Python 3.10 版、Pytorch 2.1.0 版本、CUDA 版本 11.8，是Windows。

**Comment by WangXiuhao** [comment]
> 我没有在 windows 上测试过，不过看起来是 deepspeed 在 windows 上的安装问题，建议可以去 deepspeed github issue 看看有没有解决方案～

好的 谢谢啦！
